name: Deploy Blazor with Aspire

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Aspire containers
        run: docker compose build

      - name: Restart Aspire stack
        run: docker compose up -d
